### ISSUE TITLE
This Error Keeps on Coming

### ISSUE THREAD

**Issue by ghost** [priaid-eHealth/symptomchecker#3]
Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
> java.io.IOException: Can't write [/home/raj/AndroidStudioProjects/SymptomChecker/app/build/intermediates/multi-dex/debug/componentClasses.jar] (Can't read [/home/raj/AndroidStudioProjects/SymptomChecker/app/libs/com.fasterxml.jackson.databind.jar(;;;;;;**.class)] (Duplicate zip entry [com.fasterxml.jackson.databind.jar:com/fasterxml/jackson/databind/annotation/JacksonStdImpl.class]))

**Comment by fabiants** [comment]
Dear @rajk0304 

we can not reproduce your error message but we improved some elements of the data model and fixed the issue that once in a while random inputs might cause no outputs (or better to say inconclusive data).

If your problems still exists, please provide your adjustments to the code so that we can support you.

Have a great day
Fabian

**Comment by priaid** [comment]
P.S.: You can best contact us by e-mail: support@priaid.ch.
Kind greetings,
Your priaid team
