### ISSUE TITLE
is there a quicker way for me to just do an ajax call using the sandbox credentials?

### ISSUE THREAD

**Issue by bryancresswell** [priaid-eHealth/symptomchecker#4]
instead of going thru the SDK way can i just do a ajax call? it's much faster

**Comment by priaid** [comment]
Dear @bryancresswell 
thank you for your interest in our symptom checker.
You find the ajax example here:
https://github.com/priaid-eHealth/symptomchecker/tree/master/SampleAvatar
The only part which is not directly on the browser side is the generation of the token as this would expose your credentials. All other calls are directly from the client browser to our servers.

I hope this answers your questions. Otherwise you can also reach us by email at support@priaid.ch.

Have a great day
Fabian
