### ISSUE TITLE
Its show errors while I try to open

### ISSUE THREAD

**Issue by sagar301297** [priaid-eHealth/symptomchecker#5]
I change username & password but when I try to open through Xamp it's shows error.
![untitled](https://user-images.githubusercontent.com/36477099/41051686-6efedaa8-69d4-11e8-9d6c-775bd537a4a0.png)
![untitled1](https://user-images.githubusercontent.com/36477099/41051688-6f482e7e-69d4-11e8-915a-592752c54d92.png)

**Comment by priaid** [comment]
Please send us an e-mail to our Support Team at support@priaid.ch.

**Comment by sagar301297** [comment]
I already sent you email about my problem!
I don't know where I mistake but its shows error while I try to open in
localhost through xamp
I make changes in index.php like:username,password as per your email!
I attached photos of error & my index.php code.

Thank you!





From:

Sagar Parikh

------------------------------

M 7359944562

E  sagar.parikh69@gmail.com


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
06/07/18,
1:13:33 PM

**Comment by priaid** [comment]
Dear Sagar

the problem is in your php.ini configuration which currently does not
support the session management.

Include

session.autostart = On

and perhaps

session.use_cookies=1

in your php.ini <http://www.php.net/manual/en/ini.php>.



Or make sure that you have set in your PHP code:

session_start();

PHP: session_start - Manual
<http://php.net/manual/en/function.session-start.php>



We channel all support mailings over  support@priaid.ch to ensure that we
keep up with the quality you expect.


Kind regards
Fabian from priaid




2018-06-07 9:44 GMT+02:00 sagar301297 <notifications@github.com>:

> I already sent you email about my problem!
> I don't know where I mistake but its shows error while I try to open in
> localhost through xamp
> I make changes in index.php like:username,password as per your email!
> I attached photos of error & my index.php code.
>
> Thank you!
>
>
>
>
>
> From:
>
> Sagar Parikh
>
> ------------------------------
>
> M 7359944562
>
> E sagar.parikh69@gmail.com
>
>
> [image: Mailtrack]
> <https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=
> signaturevirality5&>
> Sender
> notified by
> Mailtrack
> <https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=
> signaturevirality5&>
> 06/07/18,
> 1:13:33 PM
>

**Comment by ore-codes** [comment]
I have this same issue and I have no access to my php.ini file
